Send mail to inactive users
ae-utbm/sith pull request #861
Opened 2024-10-06 11:33 UTC by imperosol

Le bureau veut vider les comptes inactifs depuis 2 ans ou plus (c'est rigolo, parce que ça fait aussi 2 ans que le bureau demande ça).

On va le faire pour de vrai cette fois. Pour couper le taff, on va le faire en deux étapes :

1. Implémenter l'envoi automatique des mails aux utilisateurs inactifs (c'est cette PR)
2. Quand les mails seront partis, on aura quelques semaines de marges pour implémenter le vidage à proprement parler.

2024-10-06 21:04 UTC, klmp200 requested changes
Plutôt pas mal

2024-10-06 21:04 UTC, klmp200 commented on core/models.py
> +        with transaction.atomic():
Je vois que ça a juste été déplacé mais franchement on comprend rien de à quoi ça sert.
Si tu sais pourquoi on s'enmerde à faire tout ça, un petit commentaire ce serait cool. Sinon tant pis

2024-10-06 21:04 UTC, klmp200 commented on core/models.py
> +class NewManager(models.Manager):
NewManager ? Franchement on sait pas à quoi ça sert. T'as un nom plus explicite ?

2024-10-06 21:11 UTC, imperosol commented on core/models.py
> +        with transaction.atomic():
C'est les règles normales de placement dans un modèle Django. C'est juste que jusqu'ici le linter l'avait pas vu, parce que ça n'hérite pas directement de models.Model.

2024-10-10 14:10 UTC, klmp200 submitted a review, later dismissed

2024-10-12 06:55 UTC, klmp200 approved these changes

2024-10-12 13:33 UTC, merged