improve ci (to squash)
ae-utbm/sith pull request #893
Opened 2024-10-15 10:33 UTC by imperosol

Amélioration de la CI.

Si possible, on va essayer de la rendre plus rapide.

2024-11-10 23:21 UTC, klmp200 requested changes
À part ça c'est tip top

2024-11-10 23:21 UTC, klmp200 commented on .github/workflows/deploy.yml
> +          poetry run ./manage.py collectstatic --clear --noinput
On veut garder le --clear-generated, ça clear le dossier generated pour être certain qu'il ne reste pas d'artefact des versions précédentes.
--clear ça ne clear que le dossier d'output de static

2024-11-10 23:21 UTC, klmp200 commented on .github/workflows/taiste.yml
> +          poetry run ./manage.py collectstatic --clear --noinput
Pareil ici pour --clear-generated

2024-11-11 11:48 UTC, imperosol commented on .github/workflows/taiste.yml
> +          poetry run ./manage.py collectstatic --clear --noinput
Je résouds ce message, on continue la discussion sur l'autre

2024-11-11 11:59 UTC, imperosol commented on .github/workflows/deploy.yml
> +          poetry run ./manage.py collectstatic --clear --noinput
Alors justement non. La compilation des statics plante systématiquement au déploiement. On est obligé d'aller dans la console pour relancer. Et là ça marche.

Et j'ai l'impression qu'en retirant le `--clear-generated`, ça remarche.

Si jamais ça replante, je remets le flag et j'enquête plu profondément.

2024-11-11 12:28 UTC, klmp200 commented on .github/workflows/deploy.yml
> +          poetry run ./manage.py collectstatic --clear --noinput
Il y a baleine sous gravillon, c'est étrange
M'enfin, j'ai vérifier et le --clean devrais suffire, c'est juste qu'on aura des fichiers doublons sur la prod, c'est pas bien grave.

2024-11-11 12:28 UTC, klmp200 approved these changes

2024-11-11 12:28 UTC, merged