Improve ajax select
ae-utbm/sith pull request #899
Opened 2024-10-18 21:52 UTC by klmp200

On crée une classe de base avec des attributs de configuration dans le web-component, ça fait que ça ressemble vachement plus à un vrai élément html.

En plus, on corrige un bug d'affichage sur les navigateurs basés sur webkit et chromium.

Petit fix dans webpack aussi où ça plantait sur les dossiers à plus de 2 de profondeur.

2024-10-19 23:01 UTC, imperosol commented on core/static/webpack/core/components/ajax-select-index.ts
> +      },
Est-ce que ça serait extractable dans une fonction à part plus générique, qui arriverait à faire ça quel que soit la route utilisée ? Comme ça, dans le UserAjaxSelect, on fournit que la route nécessaire. Et si on crée d'autre select comme ça, ça simplifie le travail.

2024-10-19 23:04 UTC, klmp200 commented on core/views/forms.py
> +            "csss": [
C'était pour indiquer que c'est css mais au pluriel

2024-10-20 11:39 UTC, imperosol commented on core/views/forms.py
> +            "csss": [
ouimécépadansladoc
https://docs.djangoproject.com/fr/4.2/topics/forms/media/#css

2024-10-20 11:40 UTC, klmp200 commented on core/static/webpack/core/components/ajax-select-index.ts
> +      },
Tranquille, ça avance :)

2024-10-20 12:52 UTC, imperosol requested changes

2024-10-20 12:52 UTC, imperosol commented on core/lookups.py
>  class UsersLookup(RightManagedLookupChannel):
```suggestion
@deprecated("Useful message explaining the migration")
@register("users")
class UsersLookup(RightManagedLookupChannel):
```

2024-10-20 12:52 UTC, imperosol commented on counter/api.py
> +        return Group.objects.filter(name__icontains=search).values()
Pourquoi le GroupController est dans counter ?

2024-10-20 12:52 UTC, imperosol commented on counter/api.py
> +        return Group.objects.filter(name__icontains=search).values()
Le queryset n'est pas trié

2024-10-21 11:44 UTC, klmp200 commented on core/lookups.py
>  class UsersLookup(RightManagedLookupChannel):
Pas de fichier, pas de deprecated :P

2024-10-21 11:44 UTC, klmp200 commented on core/static/webpack/core/components/ajax-select-index.ts
> +      },
Normalement c'est bon comme ça

2024-10-21 11:46 UTC, klmp200 commented on counter/api.py
> +        return Group.objects.filter(name__icontains=search).values()
Ça reprend exactement comment l'ancien lookup fonctionnait, si on veut améliorer ça, ce serait dans une autre PR

2024-10-21 13:57 UTC, klmp200 commented on counter/api.py
> +        return Group.objects.filter(name__icontains=search).values()
Je me suis trompé, je l'ai déplacé déjà

2024-10-21 13:58 UTC, klmp200 commented on core/views/widgets/select.py
> +class AutoCompleteSelect(AutoCompleteSelectMixin, Select): ...
Pas spécialement, en plus j'ai pas vraiment besoin puisque j'ai déjà fait les classes de base multi et simple

2024-10-23 16:52 UTC, imperosol requested changes

2024-10-23 16:52 UTC, imperosol commented on core/templates/core/widgets/autocomplete_select.jinja
> +</{{ component }}>
Saute des lignes, stp. Les if et les for qui commencent en fin de ligne, c'est pas naturel.

2024-10-23 16:52 UTC, imperosol commented on core/views/widgets/markdown.py
> +        return context
Est-ce que c'est faisable de plutôt le faire avec la class Media, comme dans la doc de django ?

2024-10-23 16:52 UTC, imperosol commented on core/views/widgets/select.py
> +            adapter = TypeAdapter(list[self.schema])
A éviter, la création du TypeAdapter dans la fonction (cf. [ici](https://docs.pydantic.dev/latest/concepts/type_adapter/#parsing-data-into-a-specified-type) et [là](https://docs.pydantic.dev/latest/concepts/performance/#typeadapter-instantiated-once))

2024-10-23 16:52 UTC, imperosol commented on core/views/widgets/select.py
> +            ).decode("utf-8")
Il est nécessaire, le decode ?

2024-10-23 16:52 UTC, imperosol commented on core/views/widgets/select.py
> +                    ).all()
Ca pourrait être bien d'extraire ça dans un membre `queryset` et/ou dans une méthode `get_queryset`.

2024-10-28 17:00 UTC, klmp200 commented on core/views/widgets/select.py
> +            ).decode("utf-8")
La doc de pydantic dit qu'ils renvoient du binaire et c'est comme ça, on a qu'a décodé (je paraphrase).

Passer du binaire au widget comme données initiales ce serait incohérent vis à vis de comment toute l'api est en plaintext, je suis pas favorable.

2024-11-10 12:15 UTC, imperosol approved these changes

2024-11-10 12:37 UTC, merged