Casser counter click étape 1 : introduire des fragments
ae-utbm/sith pull request #921
Opened 2024-11-14 15:19 UTC by klmp200

CounterClick est gros, CounterClick est dangereux, CounterClick est important.

Ce serait judicieux de le splitter en plusieurs petits morceaux pour le rendre plus digeste, plus extensible, plus rapide et plus testable.

La première étape ici c'est de sortir la gestion du formulaire des cartes étudiantes et de la déléguer à une autre vue.

Dépend de https://github.com/ae-utbm/sith/pull/920

2024-11-14 16:18 UTC, Hyask reviewed
Sur le principe, c'est très cool, mais je sais pas trop pourquoi tu veux que je review ça. Déjà la partie NFC, j'étais plus là quand tu l'as ajouté, et je l'ai jamais vu fonctionner XD

Sur le côté architectural, ça semble OK, mais pareil, webpack j'ai jamais touché, typescript non plus, donc c'est quand même limité :-)

2024-11-14 16:20 UTC, klmp200 commented
> Sur le principe, c'est très cool, mais je sais pas trop pourquoi tu veux que je review ça. Déjà la partie NFC, j'étais plus là quand tu l'as ajouté, et je l'ai jamais vu fonctionner XD
> 
> Sur le côté architectural, ça semble OK, mais pareil, webpack j'ai jamais touché, typescript non plus, donc c'est quand même limité :-)

C'est que le dernier commit qui est important ici :)
Comme j'ai dit dans la description ça dépend d'une autre pull request :)
Merci pour la review au moins au niveau de l'architecture, ça fait plaisir :D

2024-11-19 00:00 UTC, imperosol requested changes

2024-11-19 00:00 UTC, imperosol commented on counter/templates/counter/counter_click.jinja
> +        ></div>
Est-ce que c'est nécessaire de lazy-load, ici. Est-ce qu'on peut faire un chargement initial qui ne fait pas de requête HTTP en plus tant qu'on ne soumet pas le formulaire ?

2024-11-19 20:29 UTC, klmp200 commented on counter/templates/counter/counter_click.jinja
> +        ></div>
Je suis pas certain qu'on puisse faire ça
Parce que pour mettre ce fragment, faut que je génère le template en appelant mon propre backend avec django, je sais pas trop si on peut faire ça ni si même c'est judicieux de le faire

2024-11-21 18:52 UTC, klmp200 commented on counter/templates/counter/counter_click.jinja
> +        ></div>
J'ai regardé comment faire pour mettre un formulaire directement
Conclusion: pour avoir un truc cohérent, c'est beaucoup de boulot pour une vue qui ne fonctionne de toute façon pas sans javascript.
J'ai mis une roue de chargement, je pense que c'est un bon compromis

2024-11-30 11:55 UTC, imperosol requested changes
Le formulaire affiche les UIDs des cartes, avec presque pas de contexte supplémentaire (par exemple, il n'y a pas la date d'ajout).

Les barmen ne peuvent pas supprimer une carte étudiante.

Il y a trop de code dans counter/views.py.

2024-11-30 11:55 UTC, imperosol commented on counter/templates/counter/add_student_card_fragment.jinja
> +    hx-trigger="submit"
Le `hx-trigger="submit"` sur les formulaires est implicite. Il n'est pas nécessaire.

2024-11-30 11:55 UTC, imperosol commented on counter/views.py
> +        context["counter"] = self.counter
`counter` n'est pas utilisé dans le template.

2024-11-30 11:55 UTC, imperosol commented on counter/urls.py
> +        "customer/<int:customer_id>/card/add/counter/<int:counter_id>/",
L'URL est trop longue.
`/add` ne devrait pas être donné par l'url, mais signifié par le verbe HTTP (mais pour ça, les autres urls font la même erreur, donc passe encore).

Dans l'idéal, `/counter` ne devrait pas être donné. C'est déjà le premier composant de l'URL. On peut éventuellement vouloir un comportement différent entre quand on manipule les cartes depuis un comptoir ou depuis le profil. Mais en l'occurence, ici il n'y a presque rien qui change à part la gestion des droits. Mieux vaut retirer la fin de l'URL et fusionner toutes les vues qui gèrent les cartes étus en une seule. Dans le dispatch, il y aura juste à faire une condition sur le referrer. Si la requête est envoyée depuis un comptoir, on fait la vérification des droits comptoir, sinon on fait la vérification normale.

2024-12-07 20:50 UTC, imperosol requested changes
Pour les tests qui foirent sur le assertNumQueries, c'est pas bien grave (c'est même plutôt bien si on fait mieux que prévu). Tu peux diminuer le nombre attendu.

2024-12-07 20:50 UTC, imperosol commented on counter/utils.py
> +    return counter is not None and counter.is_open
```suggestion
    return (
        Counter.objects.annotate_is_open()
        .filter(token=request.session["counter_token"], is_open=True)
        .exists()
    )
```

2024-12-07 20:50 UTC, imperosol commented on counter/tests/test_customer.py
> +        assert send_valid_request(self.client, self.club_counter.id)
Il manque pas le status code, ici ?

2024-12-08 12:46 UTC, imperosol approved these changes

2024-12-08 12:49 UTC, merged