Casser counter click étape 2 : séparer les rechargements via les fragments
ae-utbm/sith pull request #923
Opened 2024-11-15 13:55 UTC by klmp200

On continue à séparer les responsabilités de counter click en retirant les rechargements de la vue pour les mettre dans une vue dédiée.

2024-11-19 00:20 UTC, imperosol requested changes

2024-11-19 00:20 UTC, imperosol commented on counter/static/counter/js/counter_click.js
Est-ce que tu peux transformer la suppression/recréation de fichier en un déplacement/renommage ?

2024-11-19 00:20 UTC, imperosol commented on counter/views.py
> +    def get_context_data(self, **kwargs):
Le `get_context_data` a l'air d'être le même que celui du fragment des cartes étus. C'est redondant dans le code et à l'exécution (on demande à récupérer les mêmes infos, mais dans deux requêtes différentes)

2024-11-19 00:20 UTC, imperosol commented on counter/views.py
> +        return res
Tu appelles `clean` avant de mettre ton comptoir, ton barman et ton client. Ca peut potentiellement casser.

2024-11-19 00:20 UTC, imperosol commented on counter/views.py
> +        return self.counter.type == "BAR" and self.customer.user in barmen
Duplication de logique de `CounterClick`

2024-11-19 00:20 UTC, imperosol commented on counter/views.py
> +        return reverse_lazy(
Pas besoin du lazy.

2024-12-15 18:05 UTC, imperosol requested changes

2024-12-15 18:05 UTC, imperosol commented on counter/views/click.py
> +        return self.counter.type == "BAR" and self.customer.user in barmen
C'est une duplication de la logique qui est dans CounterClick.

2024-12-15 20:49 UTC, klmp200 commented on counter/api.py
> +        return self.get_object_or_exception(Customer, pk=customer_id)
Je veux pas donner trop d'infos sur le customer parce que c'est une vue disponnible aux barmen et que c'est sensé rester un peu secret.

Je vais tout mettre sauf la liste des recorded_products parce que ça regarde personne cette info

2024-12-15 20:56 UTC, imperosol commented on counter/api.py
> +        return self.get_object_or_exception(Customer, pk=customer_id)
Les infos client, c'est : 

- le code client
- le solde du compte
- le numéro de compte
- la balance des consignes

Les barmen sont légitimes à avoir la totalité de ces infos.

2024-12-15 20:57 UTC, klmp200 commented on counter/api.py
> +        return self.get_object_or_exception(Customer, pk=customer_id)
Fair enough

2024-12-16 16:13 UTC, imperosol requested changes
Autant la carte étu, ça me parait cohérent d'en avoir fait un fragment, autant je suis beaucoup moins convaincu pour le rechargement.

C'est quelque chose qui est assez étroitement couplé avec les données client utilisées pour la transaction. Là, on est obligé de faire une deuxième requête pour rafraichir les données client, alors que techniquement, si on sait que la requête a réussi, on sait quel est le nouveau solde de l'utilisateur.

C'est aussi assez bizarre d'avoir un GET sur les données client dans l'API, mais pas le POST pour le rechargement.

Etant donné que là, le formulaire de rechargement est très simple et doit être très lié au reste des données présentes sur la page, est-ce que ça serait pas plus simple de le passer complètement en Alpine ?
Ca pourrait faciliter la suite des opérations et retirer pas mal de boilerplate ici.

2024-12-16 16:13 UTC, imperosol commented on counter/views/click.py
> +        )
```suggestion
        return FormFragmentTemplateData(
            form=form_instance if form_instance else cls.form_class(),
            template=cls.template_name,
            context={
                "action": reverse_lazy(
                    "counter:refilling_create", kwargs={"customer_id": customer.pk}
                ),
            },
        )
```
Préciser le `[cls.form_class]` me parait un peu douteux. Je pense que c'est pas faux, mais c'est quand même une source de confusion pour l'analyse statique. 

Pour le typage en lui-même, on a déjà précisé le type générique de la structure en signature de la fonction, donc pas nécessaire de le remettre ici.

2024-12-16 16:13 UTC, imperosol commented on counter/views/student_card.py
> +            form=form_instance if form_instance else cls.form_class(),
Pareil que plus haut

2024-12-17 09:48 UTC, imperosol commented on counter/templates/counter/counter_click.jinja
> +              {% trans trimmed %}As a barman, you are not able to refill any account on your own. An admin should be connected on this counter for that. The customer can refill by using the eboutic.{
Comme c'est trimmed, t'es pas obligé de tout mettre sur la même ligne.

2024-12-17 09:55 UTC, imperosol approved these changes

2024-12-17 09:58 UTC, merged