Make student card unique per user
ae-utbm/sith pull request #924
Opened 2024-11-15 14:23 UTC by imperosol

Ca n'a pas réellement de sens qu'un utilisateur ait plusieurs cartes étus en simultanée. C'est plus cohérent et plus simple à gérer si on passe ça en OneToOne

2024-12-08 15:43 UTC, klmp200 requested changes

2024-12-08 15:43 UTC, klmp200 commented on counter/views/student_card.py
> +        return reverse("core:user_prefs", kwargs={"user_id": self.customer.user_id})
Ça pète pour les barmens qui veulent supprimer

2024-12-08 15:43 UTC, klmp200 commented on locale/fr/LC_MESSAGES/django.po
> +msgstr "Enregistré"
```suggestion
msgstr "Enregistrée"
```

2024-12-08 15:43 UTC, klmp200 commented on counter/templates/counter/fragments/create_student_card.jinja
> +      {% trans %}Registered{% endtrans %} <i class="fa fa-check"></i> &nbsp; - &nbsp;
Je m'attendrai ici à pouvoir overwrite la dernière carte sans utiliser le bouton de suppression

En plus c'est déjà géré par le backend

2024-12-08 15:43 UTC, klmp200 commented on counter/templates/counter/fragments/create_student_card.jinja
> +      {% trans %}Registered{% endtrans %} <i class="fa fa-check"></i> &nbsp; - &nbsp;
Aussi, j'aimerai bien avoir moyen de voir quel numéro est enregistré ainsi que la date où ça a été ajouté.

Pour pas rendre confus les utilisateurs avec un numéro compliqué, on peut faire un hover sur la checkmark, c'est utile pour les power users et pour le testing.

Sachant qu'on garde pas la même carte étudiante pendant toute ses études (si tu fait TC), savoir quand t'as changé ta carte la dernière fois c'est important.

2024-12-10 22:49 UTC, klmp200 commented on counter/templates/counter/fragments/create_student_card.jinja
> +      {% trans %}Registered{% endtrans %} <i class="fa fa-check"></i> &nbsp; - &nbsp;
Il n'y a pas de date d'ajout déjà en db alors tant pis, j'ai mis une tooltip par contre

2024-12-10 22:49 UTC, klmp200 submitted a review, later dismissed

2024-12-11 09:49 UTC, klmp200 approved these changes

2024-12-13 10:54 UTC, klmp200 submitted a review, later dismissed

2024-12-15 16:01 UTC, NaNoMelo requested changes
Juste une petite modif pour que le titre s'affiche de manière consistante et c'est tout bon !!

2024-12-15 16:05 UTC, NaNoMelo approved these changes

2024-12-15 16:06 UTC, merged