Rework the subscription page
ae-utbm/sith pull request #932
Opened 2024-11-26 15:08 UTC by imperosol

Refonte de la page pour créer des cotisations.
L'affichage dynamique où on retire les champs pour créer un nouvel utilisateur quand on en sélectionne un déjà existant est retiré et remplacé par deux formulaires entre lesquels on peut jongler. C'est à la fois plus simple à gérer pour nous (on peut bien séparer la logique en deux formulaires) et plus clair niveau UI/UX.

Ca ressemble à ça 
![image](https://github.com/user-attachments/assets/7e4ccdb9-d709-4184-beb9-bd970aa2f0b2)

La validation du formulaire se fait avec HTMX, donc pas besoin de recharger la page en cas d'erreur de validation.

Quand le formulaire de création est bon, on ne redirige plus automatiquement vers le profil utilisateur, mais on laisse le choix entre aller sur le profil, ou bien recharger la page pour créer une nouvelle cotis :

![image](https://github.com/user-attachments/assets/c1762525-05b1-4280-94c1-17d74cd6f143)

2024-11-30 18:17 UTC, klmp200 requested changes

2024-11-30 18:17 UTC, klmp200 commented on subscription/templates/subscription/subscription.jinja
> +  <div id="subscription-form" hx-ext="response-targets">
Elle sert à quoi ici l'extension response-targets ? Je ne la vois pas utilisée

2024-11-30 18:17 UTC, klmp200 commented on package.json
> +    "htmx-ext-response-targets": "^2.0.1",
Mais du coup j'ai pas l'impression qu'on se sert de cette extension

2024-11-30 18:35 UTC, imperosol commented on package.json
> +    "htmx-ext-response-targets": "^2.0.1",
En fin de compte, non. Quand j'ai commencé à réfléchir dessus, ça me paraissait une bonne idée. Mais à force de refactor mon code, j'ai fini par trouver mieux (selon moi).

Je vais retirer.

2024-11-30 18:35 UTC, imperosol commented on subscription/templates/subscription/subscription.jinja
> +    defer
ah. Ok. Bon à savoir

2024-11-30 18:37 UTC, imperosol commented on subscription/static/bundled/subscription/creation-form-existing-user-index.ts
> +      const response = await fetch(`/user/${userId}/mini/`);
J'ai pas de solution. On a mis le client d'API qui génère sa définition à partir du Swagger. Sauf que là, c'est pas du OpenAPI. Donc on retombe là où on en était avant.

Après, le composant est pas très complexe, ici, donc ça peut se réécrire complètement en Alpine+API.

2024-11-30 18:39 UTC, imperosol commented
Par contre, je suis pas ultra satisfait par le style de mes tabs. J'ai essayé de faire un truc qui prend toute la largeur à sa disposition et qui utilise des couleurs déjà présentes. Mais en fin de compte, ça rend pas si bien. Si quelqu'un a un meilleur design, je prends.

2024-12-01 17:21 UTC, imperosol commented
Nouveau style pour les tabs : 
![image](https://github.com/user-attachments/assets/98484534-d974-4319-8be3-1f79ac552a4b)

2024-12-02 08:41 UTC, klmp200 requested changes

2024-12-02 08:41 UTC, klmp200 commented on subscription/templates/subscription/subscription.jinja
> +  <div id="subscription-form" hx-ext="response-targets">
T'as retiré l'extension, pense à retirher le hx-ext qui va avec

2024-12-02 08:41 UTC, klmp200 commented on core/static/bundled/htmx-index.js
> +import "htmx-ext-response-targets/response-targets";
Mais du coup, tu retire ou pas ? Parce que je vois plus ce package dans les dépendances alors ça va crash

2024-12-02 18:52 UTC, imperosol commented on core/static/bundled/htmx-index.js
> +import "htmx-ext-response-targets/response-targets";
bien vu

2024-12-02 19:53 UTC, klmp200 approved these changes

2024-12-03 18:45 UTC, merged