Remove `RealGroup` and `MetaGroup`
ae-utbm/sith pull request #935
Opened 2024-11-30 21:53 UTC by imperosol

En ajoutant automatiquement les utilisateurs aux groupes qui vont bien quand ils rejoignent ou quittent un club, on peut arrêter notre système bizarre où on doit successivement examiner les adhésions aux clubs, puis rechercher à partir de ça un groupe auquel ils n'appartiennent pas vraiment en concaténant le nom du club et "-membres" ou "-bureau".

A partir du moment où les groupes liés aux clubs deviennent gérables comme le reste, les simplifications viennent en cascade.

Cette PR n'est que la deuxième étape (la première étant #929). Si ça se passe bien, d'autres suivront.

2025-01-03 16:40 UTC, imperosol commented on club/migrations/0012_club_board_group_club_members_group.py
> +        There must be a manual cleanup after this migration.
J'ai déjà fait la liste des futurs groupes zombis. C'est bon.

2025-01-03 16:41 UTC, imperosol commented on club/models.py
> +            self.members_group = Group.objects.create(
Bonne remarque. Qui m'a fait me rendre compte qu'en réalité les view_groups des clubs n'étaient pas utilisés. Donc j'ai juste complètement retiré.

2025-01-04 15:25 UTC, klmp200 requested changes
Franchement, c'est plutôt pas mal, à part les points soulignés, j'ai pas vraiment trouvé d'autre problème pour l'instant, c'est cool.

2025-01-04 15:25 UTC, klmp200 commented on club/tests.py
> +        assert not self.subscriber.groups.contains(self.club.board_group)
Il faudrait un test pour vérifier que changer le nom du club ça change le nom du groupe lié

2025-01-04 15:25 UTC, klmp200 commented on club/models.py
> +            self.home.name = self.unix_name
Tu oublie de renommer le groupe lié
J'ai fait des tests et le groupe reste bien lié comme il faut et il fonctionne toujours mais il garde l'ancien nom :/

2025-01-04 15:25 UTC, klmp200 commented on club/models.py
> +            self.home.save()
Il arrive quoi aux fichiers qui étaient dans la home avant ? Ils sont déplacés ? J'ai pas l'impression :/

2025-01-04 15:25 UTC, klmp200 commented on club/models.py
> +        if self.home:
Mais du coup, si je comprend bien, si il y avait déjà une home et qu'on change le nom, le dossier reste avec le même nom

2025-01-04 15:48 UTC, imperosol commented on club/models.py
> +        if self.home:
jsp

2025-01-04 15:49 UTC, imperosol commented on club/models.py
> +            self.home.save()
Normalement, ils restent liés au club. J'ai pas réellement creusé de ce côté.

2025-01-04 15:49 UTC, imperosol commented on club/models.py
> +            self.home.name = self.unix_name
corrigé

2025-01-04 15:50 UTC, klmp200 commented on club/models.py
> +            self.home.save()
À gérer une autre fois cette histoire de home

2025-01-04 15:51 UTC, klmp200 commented on club/models.py
> +        if self.home:
Pareil que précédement, on verra ça quand on travaillera dessus pour de vrai

2025-01-04 15:59 UTC, klmp200 approved these changes
On continue dans la lignée des pull request terrifiantes

2025-01-04 16:13 UTC, merged