Use .env for project configuration
ae-utbm/sith pull request #971
Opened 2024-12-24 14:41 UTC by imperosol

2025-01-25 15:35 UTC, klmp200 requested changes

2025-01-25 15:35 UTC, klmp200 commented on docs/tutorial/install.md
> +            gettext git redis
On peut garder redis en install avancée stp ?
C'est vraiment pas ouf un service en plus pour dev en local, on a déjà assez de trucs.
Surtout que pour le coup le cache en mode debug ça pose pas tellement de soucis pour tester

2025-01-25 15:35 UTC, klmp200 commented on docs/tutorial/install.md
> +Une fois les dépendances installées, il faut encore
C'est ici l'occasion de faire en sorte qu'on ai plus à créer de fichier du tout quand on est en développement

2025-01-25 15:35 UTC, klmp200 commented on sith/settings.py
> +SECRET_KEY = env.str("SECRET_KEY")
Je pense que les valeurs par défaut du `.env.example` ça devrais être set ici pour tout.
Et aussi faire que ce fichier de settings ait les valeurs par défaut pour le mode développement.

Je pense que quand tu dev, tu devrais pas à avoir à créer un .env sauf si t'as un truc spécifique à faire

2025-01-25 15:35 UTC, klmp200 commented on sith/settings.py
> +
Il faudrait aussi `CSRF_TRUSTED_ORIGINS`
J'en ai souvent besoin quand je test des features https sur mobile en local

2025-01-25 15:35 UTC, klmp200 commented on sith/settings.py
> +SITH_URL = env.str("SITH_URL", default="127.0.0.1:8000")
T'as moyen de set ce défaut à partir de la commande runserver ? Ce serait cool

2025-01-25 15:35 UTC, klmp200 commented on sith/settings.py
> +DEBUG = env.bool("DEBUG", default=False)
Suivant la manière dont je propose de gérer les choses, le default ici ça devrait être True

2025-01-25 15:35 UTC, klmp200 commented on docs/tutorial/install.md
> +Une fois les dépendances installées, il faut encore
Toute cette partie ça devrais être dans une section plus avancée

2025-01-25 17:27 UTC, imperosol commented on sith/settings.py
> +DEBUG = env.bool("DEBUG", default=False)
Au contraire. Là, par défaut on est en mode production. Ce qui signifie que ça demande moins de config en CI et que si le .env est mal configuré en prod, c'est moins dangereux.

En local, si la personne fait bien son `cp`, le mode debug sera activé, donc ça marchera

2025-01-25 17:29 UTC, imperosol commented on sith/settings.py
> +SITH_URL = env.str("SITH_URL", default="127.0.0.1:8000")
Non, j'ai pas.
Pour la très bonne raison que `SITH_URL`, c'est ce qui est utilisé dans le populate. Et le populate est appelé avant le runserver quand on installe le projet.

2025-01-25 17:33 UTC, imperosol commented on sith/settings.py
> +SECRET_KEY = env.str("SECRET_KEY")
C'est une ligne à faire au moment de l'install. C'est plus court que ce qu'on fait maintenant.

Je préfère que les valeurs par défaut aient le moins d'incidence possible sur la prod en cas de mauvaise configuration. Une ligne à taper, je trouve que c'est un prix acceptable pour un peu plus de sécurité.

2025-01-25 17:34 UTC, imperosol commented on docs/tutorial/install.md
> +Une fois les dépendances installées, il faut encore
Créer un .env maison, c'est plutôt courant. Au bout d'un moment, on peut pas simplifier à l'extrême.

2025-01-25 17:43 UTC, imperosol commented on docs/tutorial/install.md
> +            gettext git redis
Ca permet quand même d'être au plus proche de la prod.
Et comme maintenant les paramètres de connexion de Redis sont renseignés en même temps que tout le reste, ça permet de l'utiliser avec pratiquement pas de config en plus (juste `systemctl enable redis` ; c'est pas xapian, quoi).

Ca rend redis plus facile à utiliser dans la CI.
Et comme ça le rend assez simple pour être installé directement, ça permet de ne pas se limiter sur les fonctionnalités de redis ou sur les librairies qui peuvent fonctionner avec redis (celery, \*clin d'oeil\* \*clin d'oeil\*)

2025-02-17 12:36 UTC, klmp200 approved these changes

2025-02-17 12:37 UTC, merged