Unified calendar
ae-utbm/sith pull request #975
Opened 2024-12-28 17:57 UTC by klmp200

Utiliser un presta externe pour afficher les événements c'est un peu triste, surtout quand on peut tout faire maison.

* Correction de bugs de la com
* Génération d'un ICS pour les news internes
* Scrap de l'agenda de google agenda pour le redéployer en interne et éviter les cross domain request
* Agenda unifié des événements google agenda et des news du sith

2025-01-04 17:13 UTC, imperosol requested changes

2025-01-04 17:13 UTC, imperosol commented on com/templates/com/news_list.jinja
> +      {%- if user.was_subscribed -%}
les droits ont changé, là.

2025-01-04 17:17 UTC, klmp200 commented on pyproject.toml
> +ics = "^0.7.2"
Bof bof mais pour ce qu'on fait c'est pas non plus très grave
L'alternative c'est https://github.com/collective/icalendar et c'est plus chiant

2025-01-04 17:19 UTC, klmp200 commented on com/api.py
> +        return send_raw_file(IcsCalendar.get_internal())
Pas certain que ce soit une super solution parce qu'on est dans le dossier MEDIA et on veut vraiment pas faire de bêtises avec.
Et puis là il faut le générer si il existe pas, faut bien le faire à un moment

2025-01-04 17:19 UTC, klmp200 commented on com/models.py
> +            - (timedelta(days=30) * 60),  # Roughly get the last 6 months
Ah, voilà, je cherchais à faire ça

2025-01-04 22:22 UTC, imperosol commented on com/api.py
> +        return send_raw_file(IcsCalendar.get_internal())
Tout est dans le dossier media, t'inquiète. La séparation, elle se fait dans les sous-dossiers.
On a déjà certains sous-dossiers de MEDIA qui sont publics.

Pour la génération, c'est pas grave. Ca fera 404 la première fois. Et quand les gens créeront des événements, ça fera un fichier.

2025-01-04 22:40 UTC, imperosol commented on com/calendar.py
> +            - (timedelta(days=30) * 60),  # Roughly get the last 6 months
```suggestion
end_date__gte=timezone.now() - relativedelta(months=6)
```

2025-01-05 00:45 UTC, imperosol approved these changes

2025-01-05 00:46 UTC, merged